server:
    port: 9401
spring:
    profiles:
        active: dev
    application:
        name: oauth2-server
    cloud:
        nacos:
            discovery:
                server-addr: 192.168.1.114:8848
    redis:
        database: 5
        port: 6379
        host: 192.168.1.114
        password: smart@travel